export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER = "GET_CURENT_USER";

export const GET_STUDENT_DETAILS = "GET_STUDENT_DETAILS";
export const ENABLE_STUDENT_DETAILS_LOADING = "ENABLE_STUDENT_DETAILS_LOADING";
export const DISABLE_STUDENT_DETAILS_LOADING = "DISABLE_STUDENT_DETAILS_LOADING";

export const GET_ROOM_ACTION = "GET_STUDENT_DETAILS";
export const ENABLE_ROOM_ACTION_LOADING = "ENABLE_STUDENT_DETAILS_LOADING";
export const DISABLE_ROOM_ACTION_LOADING = "DISABLE_STUDENT_DETAILS_LOADING";

